### ISSUE TITLE
Empty Directories Created During Testing  

### ISSUE THREAD

**Issue by vladislavalerievich** [automl/amltk#275]
**Describe the bug**
When running `pytest` from the root directory to execute all tests, empty directories with names like "trial-trial_-1-2024-03-27T16:24:11.206972" are created.

**Expected behavior**
No extraneous directories should be created during the execution of `pytest`.

**Screenshots**
![image](https://github.com/automl/amltk/assets/23447050/236465d7-9d04-4d0a-bf7c-067b14a74b2a)

**Environment and Installation:**
- OS: Windows 10 (Host), WSL Ubuntu 22.04 (Guest VM)
- Environment: Virtual environment
- Python version: 3.10.12

**To Reproduce**
1. Install the necessary dependencies.
2. Activate the virtual environment located inside the Ubuntu-22.04 VM.
3. Execute `pytest` from the root directory of the project.
4. Observe the creation of empty directories.

**Additional context**
- The issue is observed when running all tests using `pytest`.
- It appears to be related to the execution of code involving TensorBoard callbacks or trial tracking e.g. testing the optimizers.
- These empty directories clutter the project directory and should not be created during testing.
- Investigation into the code related to TensorBoard callbacks or trial tracking during test execution is necessary to identify the root cause of the issue.
- Potential solutions may involve modifying the test setup to prevent the execution of code that leads to the creation of these directories.

This issue impacts the cleanliness and organization of the project directory during testing and should be addressed to improve the testing experience.

**Comment by vladislavalerievich** [comment]
After updating sklearn to the new version, the error disappeared. No new directories were created during test run.


![image](https://github.com/automl/amltk/assets/23447050/78054a85-5d68-4974-8675-908362e32aca)

**Comment by eddiebergman** [comment]
This issue seems to have dissapeared? However as seen in the screenshot, there are still issues with the `dask_executor` which only seem to appear on windows.
